services:
  damnfast-api:
    build: .
    container_name: damnfast-api
    restart: unless-stopped

    environment:
      - TZ=America/Santiago
      - DB_HOST=damnfast-db
      - DB_NAME=dashboard_db
      - DB_USER=postgres
      - DB_PASSWORD=secretpassword
      - ADMIN_USER=${ADMIN_USER}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}

    networks:
      - cloudflare_net

    volumes:
      - ./app/assets:/app/app/assets

  damnfast-db:
    image: postgres:15-alpine
    container_name: damnfast-db
    restart: unless-stopped
    environment:
      - POSTGRES_DB=dashboard_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secretpassword
      - TZ=America/Santiago
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - cloudflare_net

  damnfast-dashboard:
    build:
      context: ./dashboard
    container_name: damnfast-dashboard
    restart: unless-stopped
    environment:
      - DB_HOST=damnfast-db
      - DB_NAME=dashboard_db
      - DB_USER=postgres
      - DB_PASSWORD=secretpassword
      - ADMIN_USER=${ADMIN_USER}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - FLASK_SECRET_KEY=super-secret-key-13579
      - TZ=America/Santiago
    depends_on:
      - damnfast-db
    volumes:
      - ./app/assets:/app/app/assets
    networks:
      - cloudflare_net

  damnfast-nginx:
    image: nginx:1.27-alpine
    container_name: damnfast-nginx
    restart: unless-stopped
    ports:
      - "9005:80"
    depends_on:
      - damnfast-api
      - damnfast-dashboard
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - cloudflare_net

volumes:
  pgdata:

networks:
  cloudflare_net:
    external: true
    name: cloudflare_network
